# Site settings
title: MDM Capital Management
email: hmurchie@mdmcapital.management
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

destination: /var/www/mdmcapital.management/public_html

twitter_username:

# Build settings
markdown: kramdown
